[package]
name = "mpl-token-metadata"
version = "1.13.0"
description = "Metaplex Metadata"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/metaplex-program-library"
license-file = "../../LICENSE"
edition = "2021"
readme = "README.md"

[features]
no-entrypoint = []
test-bpf = []
serde-feature = ["serde", "serde_with"]

[dependencies]
arrayref = "0.3.6"
borsh = "0.9.2"
mpl-token-auth-rules = { version = "1.1", features = ["no-entrypoint"] }
mpl-token-metadata-context-derive = { version = "0.2.1", path = "../macro" }
mpl-utils = "0.3.0"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0.149", optional = true }
serde_with = { version = "1.14.0", optional = true }
shank = { version = "0.0.11" }
spl-associated-token-account = { version = "1.1.1", features = ["no-entrypoint"] }
solana-program = "~1.14.13"
spl-token-2022 = "~0.6.0"
thiserror = "1.0"

[dev-dependencies]
async-trait = "0.1.64"
old-token-metadata = { package = "mpl-token-metadata", version = "=1.10.0", features = ["no-entrypoint"] }
rmp-serde = "1.1.1"
rooster = { path = "/Users/febo/Developer/metaplex-foundation/rooster/program" }
serde = { version = "1.0.147", features = ["derive"]}
solana-sdk = "~1.14.13"
solana-program-test = "~1.14.13"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
test-case = "3.1.0"

[lib]
crate-type = ["cdylib", "lib"]
