[package]
name = "mpl-token-metadata"
version = "2.0.0-beta.1"
description = "Metaplex Metadata"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/metaplex-program-library"
license-file = "../../../LICENSE"
edition = "2021"
readme = "README.md"

[features]
no-entrypoint = []
test-sbf = []
serde-feature = ["serde", "serde_with"]

[dependencies]
arrayref = "0.3.6"
borsh = "~0.10.3"
mpl-token-auth-rules = { version = "1.4.2", features = ["no-entrypoint"] }
mpl-token-metadata-context-derive = { version = "0.3.0", path = "../macro" }
mpl-utils = "0.3.1"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0.149", optional = true }
serde_with = { version = "1.14.0", optional = true }
shank = { version = "0.0.11" }
solana-program = "~1.16.5"
spl-token = { version = ">= 3.5.0, < 5.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = ">= 1.1.3, < 3.0", features = ["no-entrypoint"] }
thiserror = "1.0"

[dev-dependencies]
async-trait = "0.1.64"
rmp-serde = "1.1.1"
rooster = { git = "https://github.com/metaplex-foundation/rooster", features = ["no-entrypoint"] }
serde = { version = "1.0.147", features = ["derive"]}
solana-sdk = "~1.16.5"
solana-program-test = "~1.16.5"

[lib]
crate-type = ["cdylib", "lib"]
