name: Install Themis
description: Installs Themis CLI

runs:
    using: "composite"
    steps:
      - name: Download binary
        shell: bash
        run: |
          bash <(curl -sSf https://raw.githubusercontent.com/metaplex-foundation/themis/main/scripts/install.sh)
          echo $(themis -V)
